//AUTOGENERATED FILE FROM png2mtspr
#define detective_TILE_H 16
#define detective_WIDTH 16
#define detective_HEIGHT 16
#define detective_PIVOT_X 8
#define detective_PIVOT_Y 8

extern const UINT8 detective_data[192];
extern const metasprite_t* const detective_metasprites[3];
