/*
    CELLAR_2_TILES.H
    Generated by gb_map_converter v1.2.
*/

#ifndef __MAP_CELLAR_2_TILES_H__
#define __MAP_CELLAR_2_TILES_H__

#define CELLAR_2_TILE_COUNT 24

#define CELLAR_2_PALETTE 0x1B

extern const void __bank_CELLAR_2_TILE_DATA;

extern const unsigned char CELLAR_2_TILE_DATA[];

#endif
